### ISSUE TITLE
[FEATURE] Add option to disable focus in certain filetypes

### ISSUE THREAD

**Issue by NTBBloodbath** [beauwilliams/focus.nvim#12]
Hi, thank you for creating this lib, the truth has been very useful :slightly_smiling_face: but there is a small detail ... I would like to be able to have an option to disable focus on certain filetypes since I use some plugins like [Vista.vim](https://github.com/liuchengxu/vista.vim) and when using focus the Vista view is messed up when I open multiple buffers at the same time (like NvimTree and Vista) :confused:

[![Screenshot-20210220-214211.png](https://i.postimg.cc/WpybtCqx/Screenshot-20210220-214211.png)](https://postimg.cc/QVpry6bq)

**Comment by beauwilliams** [comment]
Hi there :)

Thanks for the positive feedback! Happy to hear that some people are finding focus to be useful. 

I can absolutely look into adding this feature, it seems like a sensible request so it has my vote

**Comment by beauwilliams** [comment]
Okay, so I have had some issues on my end confirming if this is working. 

I also did some more testing and noticed sometimes when you have minimal screen real estate, and try to open too many windows it can sort of 'crush' the other windows in view. I think this is normal vim behaviour in that instance. E.g I tried opening NerdTree, NvimTree and CHADTree all at once and it ended up messing them up even with focus disabled.

I have pushed some commits to this branch, that should allow for defining custom filetypes. https://github.com/beauwilliams/focus.nvim/tree/cust_filetypes

Let me know what you think :)

**Comment by beauwilliams** [comment]
So for example we open a new buffer, make a split, run :lua vim.o.winwidth=120 to resize our main window, open NvimTree open NERDTree and then switch (ctrl-w) back to our original split we can see that the NERDTree has shrunk due to the fact there is not enough width to accommodate all the windows

At least this is the behaviour I am finding on my end right now 🤔

**Comment by NTBBloodbath** [comment]
Hi, really thank you very much for the improvements, I still had some problems with Vista when opening the same windows but I reduced the width to 60 and now they all work like a charm :slightly_smiling_face: 

[![Screenshot-20210223-091506.png](https://i.postimg.cc/g22KJh2C/Screenshot-20210223-091506.png)](https://postimg.cc/YhTFDhgR)

**Comment by NTBBloodbath** [comment]
So in itself the changes work, it would only be to play a little with the width according to the size of the screen and the number of windows that will be opened, but that already by the user :thinking:

**Comment by beauwilliams** [comment]
Okay wonderful, I think for the meantime we could go with these changes?

I can have another think about how we might deal with limited screen real estate but its fair to say that can be up to the user to reduce the size of focus in that case ☺️

**Comment by NTBBloodbath** [comment]
Perhaps for now to give a warning that if it doesn't work it's that the screen is very small and should reduce the focus width :thinking:

For example, right now I'm on a 1368x768 monitor but due to problems with the Nvidia drivers I have to boot without them and that leaves me with a resolution of 1024x768, which is really small and made me reduce the focus width a little more to so it works

**Comment by beauwilliams** [comment]
Great idea! I will be sure to add this to the readme then. Let me get onto it right away.

Fingers crossed most users are not stuck with such a small resolution. But glad that there is still enough space for you there to make focus still useful 😁
