### ISSUE TITLE
Behaviour on terminal's window resize

### ISSUE THREAD

**Issue by timsofteng** [beauwilliams/focus.nvim#13]
Hello. I'm looking on substitute for vim-maximizer plugin which is pretty decent but have some bad side. If I maximize window and then resize my terminal window in any way (tmux pane or whatever) and then try to restore previous layout it will of course wrong. Could your plugin to restore original layout in resized window according to changing it's proportion?

**Comment by beauwilliams** [comment]
Hey there :)

Okay so I had a look at vim-maximizer. It seems they store values of window dimensions of which my plugin does not.

Running :ToggleFocus will revert the splits to system default (e.g 50/50 split if you have two open)

And rerunning it, will resize your focussed split to the dimensions you have specified (or the default ones)

So given that running :DisableFocus or :ToggleFocus restores the default sizes based on current the screen dimension automatically, I would say this plugin would solve your issue.

Correct me if I have understood you wrong
