### ISSUE TITLE
Disable for NvimTree

### ISSUE THREAD

**Issue by andreicorpo** [beauwilliams/focus.nvim#15]
Hello, first of all, nice job with this plugin!

I am wondering if it would be possible to disable the focus for NvimTree. I don't really need it to be resized. Thanks!

**Comment by beauwilliams** [comment]
Thanks so much! Glad you are enjoying focus so far.

I can definitely look into fixing that. It shouldn't be the case as is. I'll do some testing and try to produce the issue & fix it.

**Comment by beauwilliams** [comment]
@andreicorpo Can you please confirm this is still an issue for you? I'm unable to replicate the bug on my end at the moment. I'll think about how I can produce it later, just want your confirmation its still a problem for you.

**Comment by beauwilliams** [comment]
I've now fixed this issue and it should no longer resize when nvim tree is opened 👍  

https://github.com/beauwilliams/focus.nvim/commit/b7a5ca1cb0810f3bff6933c880973c75d8aac528

**Comment by zbouslikhin** [comment]
Hey @beauwilliams, has this also fixed CHADTree?

**Comment by zbouslikhin** [comment]
> Hey @beauwilliams, has this also fixed CHADTree?
> Regardless, My CHADTree window is still being resized.

Self answering my question; It does work, but I'm ending up on #67.

**Comment by beauwilliams** [comment]
Sorry, can I clarify, is CHADTree being resized? @zbouslikhin

**Comment by zbouslikhin** [comment]
@beauwilliams CHADTree is not resized when first run. However, it's then resized if one starts switching between windows
![ezgif com-gif-maker](https://user-images.githubusercontent.com/47977073/146672807-d157c8ce-737c-4338-94ec-d2c4e22895af.gif)
