### ISSUE TITLE
Add a mapable focus_view_split function

### ISSUE THREAD

**Issue by cryptomilk** [beauwilliams/focus.nvim#16]
Thank you very much for this plugin.

I'm a big fan of [GoldenView](https://github.com/zhaocai/GoldenView.Vim)

I've looked for a neovim implementation and found this plugin. What I miss is a command to quickly split a window. In GoldenView you have:

```
nmap <silent> <C-L>  <Plug>GoldenViewSplit
```

Could you add something like this for focus?

**Comment by beauwilliams** [comment]
I currently have some stuff in my vimrc. using hjkl to open splits directionally
If I hit leader<l> it opens a split to the right
If I hit leader<j> it opens a split to the left 
etc...
Is this how goldenview works?
I had a quick look and was not sure exactly. Let me know :)

**Comment by cryptomilk** [comment]
The `GoldenViewSplit` is following the [Golden Spiral](https://en.wikipedia.org/wiki/Golden_spiral) for splitting windows. How it splits depends on the window orientation. If you have a portrait view, it would do a horizontal split first. If you have a landscape view it would create a vertical split first, the second would be a horizontal split.

**Comment by cryptomilk** [comment]
We have a "Day of Learning" at se end of the month. I will implement it then ...
