### ISSUE TITLE
Doesn't work with nvim-tree.lua

### ISSUE THREAD

**Issue by kevinpita** [beauwilliams/focus.nvim#17]
When I'm using focus.nvim and I open nvim-tree.lua focus.nvim stops working and even If I close my tree I have to DisableFocus and EnableFocus

![](https://i.imgur.com/hjqnEbp.gif)

**Comment by beauwilliams** [comment]
Thanks for pointing this out @kevinpita  I missed this issue earlier. I will get onto this asap and will let you know once fixed

**Comment by beauwilliams** [comment]
I have fixed this issue @kevinpita let me know if any problems mate
