### ISSUE TITLE
Not working config and issues with tokyonight

### ISSUE THREAD

**Issue by gegoune** [beauwilliams/focus.nvim#31]
Hey, trying out your plugin, like the idea so far but wasn't able to configure it to my liking yet. Please have a look at screenshot below which shows my current configuration. As you can see there are could of issues there:

1. `cursorline` gets activated (I am not enabling it at all in my configuration) even though it's set to `false`
2. `signcolumn` gets deactivated for inactive windows even though I have this option set to `false` (set to `yes:2` in my configuration)
3. some odd highlighting (making `focus` var unreadable in active window) - this is due to `focus.winhighlight = true`, but how could I darken background only for inactive windows?

<img width="889" alt="Screenshot 2021-09-08 at 00 38 02" src="https://user-images.githubusercontent.com/69750637/132419269-5cc2a3fa-2bfc-4f76-b4b9-5b238d9e73bc.png">
(please note I truncated right hand side of the terminal window, sizing is all good and working very nicely)
(note2: green vertical line is gitsigns' signs, not split characters, it ends on the last line of the file as you can just about see on screenshot)

Thanks for any hints!

**Comment by beauwilliams** [comment]
Hey there! Glad you have given focus a shot, I hope we can work out these issues.

Can I check to start with, if you set focus.enable to false, does it disable focus completely?

Regarding the highlighting, it's not something I use personally, however you should be able to set the highlight groups. I would assume its going to default to your theme if possible. 

Perhaps you can try playing around with changing the link to something else, or disable highlighting completely
```lua
vim.cmd('hi link UnfocusedWindow CursorLine')
vim.cmd('hi link FocusedWindow VisualNOS')
```

**Comment by gegoune** [comment]
> Can I check to start with, if you set focus.enable to false, does it disable focus completely?

Aha! It does not actually, focus is still active with

```lua
local focus = require 'focus'

focus.enable = false
focus.cursorline = false
focus.signcolumn = false
focus.number = false
focus.winhighlight = true
```

set in `after/plugin/focus.lua`.

**Comment by beauwilliams** [comment]
try placing the config in your init.lua to test out.

i'm not sure after/plugin loads anything except vim files

**Comment by gegoune** [comment]
> try placing the config in your init.lua to test out.

Aha! Spot on, if I move it to init.lua it works as expected. Interesting. I have all my plugin configuration in aforementioned directory and didn't encounter any problems before. Interesting.

**Comment by beauwilliams** [comment]
Awesome, glad that fixed it 👍

**Comment by gegoune** [comment]
Thanks for helping out! Would you consider adding more standard way of configuring your plugin through `setup({})` function perhaps?

**Comment by beauwilliams** [comment]
Yes so it's something I am considering. I have had a few people mention it. The main reason for not going ahead and making the change is that the plugin will stop working for all users.

I am cautious not to waste peoples time having to refactor their configs for a change that does not bring them any benefit.

**Comment by gegoune** [comment]
Fair point, but benefit would be to follow somewhat standard way of configuring nvim lua plugins.

**Comment by beauwilliams** [comment]
> Fair point, but benefit would be to follow somewhat standard way of configuring nvim lua plugins.

I've published a new branch, setup. You can take a look and let me know what you think

**Comment by gegoune** [comment]
After quick test it seems to be working very well. Thanks for doing this!
