### ISSUE TITLE
FocusSplit command with file arg provided will not open in existing window

### ISSUE THREAD

**Issue by beauwilliams** [beauwilliams/focus.nvim#32]
I.e, there is window on left, you issue :FocusSplitLeft filename.ext

It moves to the split, but does not open the file currently

**Comment by beauwilliams** [comment]
Note. The code appears just fine.

**Comment by sagarc03** [comment]
Tell me if I get this right?

* buffer with file A is open
* You are trying to open file B on the left.
* buffer with file A goes to the right
* file B is not opening

**Comment by beauwilliams** [comment]
Yep basically. It works when we create a new split, but when we are moving to existing split and attempting to open file its not working. I'm putting this issue here so I don't forget. I spent about 10 mins on it but there seems to be something else going on.
