### ISSUE TITLE
[Bug]: `FocusToggle` don't enable the plugin when called for the first time in a nvim instance

### ISSUE THREAD

**Issue by younger-1** [beauwilliams/focus.nvim#34]
### Problem:
After I started nvim with two windows in a tab, I called `:FocusToggle` and no window resized. If I I call `:FocusToggle` second time, it works. If I call `:FocusEnable` at the begining, it works too.

### Expeced behavior 
Calling `:FocusToggle` for the first time will resize windows

### 
This is my `focus` config and mapping.
```lua
{
    "beauwilliams/focus.nvim",
    cmd = { "FocusToggle" },
}
nnoremap <leader>kz <cmd>FocusToggle<cr>
```

**Comment by beauwilliams** [comment]
> ### Problem:
> 
> After I started nvim with two windows in a tab, I called `:FocusToggle` and no window resized. If I I call `:FocusToggle` second time, it works. If I call `:FocusEnable` at the begining, it works too.
> ### Expeced behavior
> 
> Calling `:FocusToggle` for the first time will resize windows
> 
> This is my `focus` config and mapping.
> 
> ```lua
> {
>     "beauwilliams/focus.nvim",
>     cmd = { "FocusToggle" },
> }
> nnoremap <leader>kz <cmd>FocusToggle<cr>
> ```

You should not be using focusToggle with lazy loading for now.

At the moment focus is loaded by default.

So when you load focus, and issue the command FocusToggle as the same time

What you are saying is load focus, and then toggle it off.

Instead I suggest using FocusEnable as your lazy load command

Once you lazy load, all the rest of the focus commands are loaded anyways

The only way to fix this is not to load focus by default, for now at least.

Perhaps there is another way. But for now the only way would be if I disabled focus by default

**Comment by younger-1** [comment]
> So when you load focus, and issue the command FocusToggle at the same time
> 
> What you are saying is load focus, and then toggle it off.
> 
> Instead I suggest using FocusEnable as your lazy load command
> 
> Once you lazy load, all the rest of the focus commands are loaded anyways
> 
> The only way to fix this is not to load focus by default, for now at least.
> 
> Perhaps there is another way. But for now the only way would be if I disabled focus by default

Thanks you. It is a workaround for me.

**Comment by beauwilliams** [comment]
I will try and think of a way to deal with this edge case but for now I will close it and add a note in the readme
