### ISSUE TITLE
Support for toggling maxed out window? 

### ISSUE THREAD

**Issue by DanielCardonaRojas** [beauwilliams/focus.nvim#35]
I find my self often working with ctrl-w + |   and ctrl-w + = to maximize and equalize splits. Does this plugin support this in a single command that would toggle both states?

If not I think I would be a nice addition. In the past I've used zoomwintab that creates a seperate tab to accomplish this.

**Comment by beauwilliams** [comment]
I can most certainly look into this. Currently we run a c-w + = when disabling focus to set the splits back to a normalised state. No reason we can't figure out a way to have just a normalise and a maximise command that works well with focus

**Comment by beauwilliams** [comment]
0f13c14

**Comment by beauwilliams** [comment]
> I find my self often working with ctrl-w + | and ctrl-w + = to maximize and equalize splits. Does this plugin support this in a single command that would toggle both states?
> 
> If not I think I would be a nice addition. In the past I've used zoomwintab that creates a seperate tab to accomplish this.

I've added the command now as well as a maximise and equalise command separately. I really like this command! Thanks for the suggestion 👍

**Comment by DanielCardonaRojas** [comment]
So would there be an easy way to toggle between maximized and equalized with a single key combo ? 

Like have ctrl + | maximize and equalize ?

**Comment by beauwilliams** [comment]
> So would there be an easy way to toggle between maximized and equalized with a single key combo ?
> 
> Like have ctrl + | maximize and equalize ?

Yeah, so you can map the command `:FocusMaxOrEqual` to whichever key shortcut you like 

Give it a go and if you have any issues let me know 👍
