### ISSUE TITLE
Feature Request: Filetypes to exclude

### ISSUE THREAD

**Issue by shaksiper** [beauwilliams/focus.nvim#36]
It would be great to specify certain filestypes to exclude from auto resize so that they can stay smaller and fixed-sized.
I can see there is good effort to exclude, for example, some of the popular file explorer tree plugins. However hardcoding them is not a good idea.
So making it a optional filetype exclusion list would be better?

**Comment by beauwilliams** [comment]
This is something that has been on the books for a while it's been left while some other things were completed. I'll get to work on it asap
