### ISSUE TITLE
Option Request: create_new_window

### ISSUE THREAD

**Issue by tricktux** [beauwilliams/focus.nvim#37]
My use case:
- I have a function that moves to the next tmux pane when we run out of windows to move to.

I would love to integrate that with this plugin. But I can't because the function already created a new window

Option would be something like:
```lua
-- If no window exists in the specified direction relative to the current window
-- then it will instead create a new blank buffer window
-- Default: true
require("focus").setup({create_new_window = false})
```

Excellent plugin BTW!

**Comment by beauwilliams** [comment]
Let me get this correct, so instead of creating splits, and moving between them you would like instead to move between tmux windows?

If you can share the function you use that would be awesome 👍

**Comment by tricktux** [comment]
Of course!


```lua
function _G.tmux_move(direction)
  vim.validate {direction = {direction, 'string'}}

  local curr_win = vim.api.nvim_get_current_win()
  vim.fn.execute('wincmd ' .. direction)
  local new_win = vim.api.nvim_get_current_win()
  if new_win == curr_win then
    vim.fn.system('tmux select-pane -' .. vim.fn.tr(direction, 'phjkl', 'lLDUR'))
  end
end

-- This is a custom function, but nvim_set_keymap would work as well
      map.nnoremap('<A-h>', [[<cmd>call v:lua.tmux_move('h')<cr>]])
      map.nnoremap('<A-j>', [[<cmd>call v:lua.tmux_move('j')<cr>]])
      map.nnoremap('<A-k>', [[<cmd>call v:lua.tmux_move('k')<cr>]])
      map.nnoremap('<A-l>', [[<cmd>call v:lua.tmux_move('l')<cr>]])
```

**Comment by beauwilliams** [comment]
I just added a commit a8e86a79169e5ae4feb49e1ee947c3823168afdf

```lua
require("focus").setup({tmux = true})
```

I will need to setup tmux but its essentially your line 
`vim.fn.system('tmux select-pane -' .. vim.fn.tr(direction, 'hjkl', 'lLDUR'))`

Except I removed the p as you can see from the phjkl, unless you think that should be there

**Comment by tricktux** [comment]
I've made a minor comment on commit above.

Other than that looks great! 👍🏻

**Comment by beauwilliams** [comment]
> I've made a minor comment on commit above.
> 
> Other than that looks great! 👍🏻

I just commented on your comment. I can add it back in. Should do no harm for now

**Comment by beauwilliams** [comment]
I will close this for now. If issues, feel free to reopen 👍
