### ISSUE TITLE
focus + scrollview  ==>  telescope problem

### ISSUE THREAD

**Issue by JoseConseco** [beauwilliams/focus.nvim#38]
I'm not sure why but only if I have both plugins :  `focus` and  [scrollview](https://github.com/dstein64/nvim-scrollview),
  then telescope promp covers the results window:

![image](https://user-images.githubusercontent.com/13521338/133000040-d0eb15e5-4204-4774-a5fc-05b78ee04fa9.png)

Problem is gone if I remove any of the two plugins.
EDIT: I noticed adding:  height=1 in focus config fixes the issue, but then anto adjusting windows height wont work. Still ok workaround.

**Comment by beauwilliams** [comment]
Hmm, I think scrollview must be doing something here. I need to check what is conflicting between the two plugins.

My guess is that scrollview will need to be added to list of ignored buffertypes, as it creates a buffer shat shows the scroller. That's my guess but it reminds me of similar behaviour in the past with telescope.

**Comment by beauwilliams** [comment]
Okay I think it's fixed. Can you please test and let me know if you find any issues. I had some weird behaviour then it just magically went away. I can't produce it again now. I will keep issue open for a while and if all good will close if the issues don't pop up again.

**Comment by JoseConseco** [comment]
Thanks beauwilliams - now all works fine.  I was not sure if it was scrollview problem or focus.

**Comment by beauwilliams** [comment]
Awesome, happy to hear its working on your end. Thanks for letting me know and closing the issue
