### ISSUE TITLE
[FEATURE] Add option to disable cursorline default

### ISSUE THREAD

**Issue by levouh** [beauwilliams/focus.nvim#4]
Is there a specific reason to have the `autocmd` to `set cursorline` on the focused window? I imagine it has something to do with making it more obvious split is currently _focused_, but either way, would it be possible to have a setting to disable it?

---

Also some food for thought, you can do something like:

```
set winhighlight=Normal:FocusedWindow,NormalNC:UnfocusedWindow
```

to actually highlight the focused split with a different color. You'd need to define the `FocusedWindow` and `UnfocusedWindow`, preferably with `:h hi-default` so that users can override them, as well as gating this behind a variable to completely disable it.

See a proposed implementation of this in #5.

---

Either way, awesome plugin, it'd just be nice to be able to configure it a bit more.

**Comment by nyngwang** [comment]
This resolves my problem :) Nice!
