### ISSUE TITLE
Problem disabling for diffview.nvim

### ISSUE THREAD

**Issue by yngwi** [beauwilliams/focus.nvim#42]
Hi,
I'm trying to use the [diffview.nvim](https://github.com/sindrets/diffview.nvim) plugin and can't seem to disable focus for the view this plugin creates. It uses a side window with the file type `DiffviewFiles` and two other windows that display the file diff before/after, both with the filetype of the source file. Even though I can add DiffviewFiles to `excluded_filetypes`, the sizes of the two diff windows get changed. Is there a way to configure this more in detail?
Best,
Daniel

**Comment by beauwilliams** [comment]
I've had a quick look and its a bit of a tough one. The two panes where the files are shown are standard, e.g they have a filetype of whatever file you are diffing.

I am thinking perhaps I can raise a PR with diffview, to set buftype variable to we can use that instead, that might work.

In the meantime, you can run :FocusToggle to get the split arrangement back. Then once you close diffview you can run :FocusToggle again

**Comment by gegoune** [comment]
Maybe some `TabEnter` autocommand with detection for diffview which would disable Focus for that tab?

**Comment by yngwi** [comment]
Thank you for your response. I am aware of the workaround I just wanted to bring this to your attention, I appreciate the effort, thanks for this great plugin.

**Comment by beauwilliams** [comment]
This will work for now while I see if I can find a better way. Place in init.lua etc or if you want init.vim if you remove the vim.cmd wrapper

```lua
vim.cmd([[
function! DiffviewFocus()
    lua vim.bo.buftype = 'help'
    :DiffviewOpen
endfunction
cnoreabbrev DiffviewOpen call DiffviewFocus()
]])
```

**Comment by beauwilliams** [comment]
> Maybe some `TabEnter` autocommand with detection for diffview which would disable Focus for that tab?

That could work 👍

**Comment by beauwilliams** [comment]
I'm thinking it would be nice to have a buftype that prevents setting of options, or perhaps just a special one for developers to use such as in this case. I find that the 'help' buftype allows saving etc so it seems fine for now. But it would be nice to have another one like 'special' for devs to use

**Comment by yngwi** [comment]
> This will work for now while I see if I can find a better way. Place in init.lua etc or if you want init.vim if you remove the vim.cmd wrapper
> 
> ```lua
> vim.cmd([[
> function! DiffviewFocus()
>     lua vim.bo.buftype = 'help'
>     :DiffviewOpen
> endfunction
> cnoreabbrev DiffviewOpen call DiffviewFocus()
> ]])
> ```

Hi again. I tried your code snippet but I couldn't see a difference unfortunately. I put it in my lua config. If I'm not mistaken (I am a noob when it comes to actual vim code, be it vimscript or lua) the snippet defines a function that basically replaces DiffviewOpen. It sets the buffer type to help before using DiffviewOpen. I have then tried to integrate it into my workflow and directly call a function as part of my keys defined with which-key in the following way:

```lua
DiffviewFocus = function()
    vim.bo.buftype = "help"
    require("diffview").open()
end
```

`d = { "<cmd>lua DiffviewFocus()<CR>", "Show the Git diff-view" }`

It seems to work as I also tried to put a print command into the function and it did print but the buffer types don't seem to be changed and the focus behavior doesn't change. Can you tell me if I did something wrong?

Best,
Daniel

**Comment by beauwilliams** [comment]
> > This will work for now while I see if I can find a better way. Place in init.lua etc or if you want init.vim if you remove the vim.cmd wrapper
> > ```lua
> > vim.cmd([[
> > function! DiffviewFocus()
> >     lua vim.bo.buftype = 'help'
> >     :DiffviewOpen
> > endfunction
> > cnoreabbrev DiffviewOpen call DiffviewFocus()
> > ]])
> > ```
> 
> Hi again. I tried your code snippet but I couldn't see a difference unfortunately. I put it in my lua config. If I'm not mistaken (I am a noob when it comes to actual vim code, be it vimscript or lua) the snippet defines a function that basically replaces DiffviewOpen. It sets the buffer type to help before using DiffviewOpen. I have then tried to integrate it into my workflow and directly call a function as part of my keys defined with _which-key_ in the following way:
> 
> ```lua
> DiffviewFocus = function()
>     vim.bo.buftype = "help"
>     require("diffview").open()
> end
> ```
> 
> `d = { "<cmd>lua DiffviewFocus()<CR>", "Show the Git diff-view" }`
> 
> It seems to work as I also tried to put a print command into the function and it did print but the buffer types don't seem to be changed and the focus behavior doesn't change. Can you tell me if I did something wrong?
> 
> Best,
> Daniel

Can you try update focus and try again. I added in support for the help buftypes yesterday. Let me know how you go 👍

**Comment by beauwilliams** [comment]
Okay this definitely works. But only when run after opening `lua require("diffview").open()`
 It is a naive way of solving the problem so that's mostly the issue
 ```lua
 FocusEqualiseDiffview = function()
    vim.cmd([[
    wincmd w
    wincmd w
    ]])
    vim.bo.buftype = "help"
    vim.cmd("FocusEqualise")
end
 ```
 Call it with `lua require("init").FocusEqualiseDiffview()` after running `lua require("diffview").open()`

**Comment by beauwilliams** [comment]
This is not working either. Its all related to the same issue I believe with blocking/non-blocking and the synchronicity of the execution of code

```vim
autocmd TabEnter DiffviewFilePanel :FocusDisable
```

If you open diffview, first run the windows are not equalised, if you switch to the other tab, and back to diffview, it will then trigger the above autocommand. Basically, its no better than my first solution right now.

**Comment by yngwi** [comment]
Hi,
thanks a lot for your commitment and help. For now I have just started do use a keybind to quickly disable/reenable focus when using diffview. Thanks again!

**Comment by beauwilliams** [comment]
No worries. That's the most straight forward way for now. It's hard to deal with some plugins

**Comment by beauwilliams** [comment]
Okay it will now equalise the windows when entering the diffview, see image below for how it should look

![](https://i.ibb.co/GM6p0fS/Screen-Shot-2021-09-17-at-3-36-51-pm.png)

**Comment by yngwi** [comment]
Hi. Thanks again but it doesn't work for me. The behavior is unchanged. Shouldn't the filetype be `DiffviewFiles` (with uppercase D and F)?, at least that's what is shown when I do `:set filetype?`.

**Comment by beauwilliams** [comment]
> Hi. Thanks again but it doesn't work for me. The behavior is unchanged. Shouldn't the filetype be `DiffviewFiles` (with uppercase D and F)?, at least that's what is shown when I do `:set filetype?`.

That is odd. I am using a :lower() function to process the filetype into lowercase.

I have just tried again, running `:lua require("diffview").open()` with the latest pull of focus.nvim and its working on my end. I am not sure why it is not on yours.

Just double checking you are on the latest pull yeah?

**Comment by yngwi** [comment]
Hm strange it is working now. I have indeed checked that I have the latest version but something still had to be off at my end. Sorry for the inconvenience and thank you for your work!

**Comment by beauwilliams** [comment]
Perfect! Thanks for letting me know and closing
