### ISSUE TITLE
FocusSplitNicely but open a terminal?

### ISSUE THREAD

**Issue by IndianBoy42** [beauwilliams/focus.nvim#44]
Or more generally allow customizing what is opened

**Comment by beauwilliams** [comment]
This can be done, let me find some time and I will work on it 👍

**Comment by beauwilliams** [comment]
Okay I have added both the capability to open files and run a command with :FocusSplitNicely and :FocusSplitRight etc

**Comment by IndianBoy42** [comment]
The example in the README.md doesn't seem to work
```
:FocusSplitNicely cmd term
```

I get a new split but it just has the same file as before

**Comment by IndianBoy42** [comment]
```
	if split_cmd == 'vsplit' and not vim.o.splitright then
```

Why do we need the condition after the `and`? I have that option set and thats why `process_split_args` isn't called

**Comment by beauwilliams** [comment]
I didn't write that part of the code, but it seems it might be unnecessary. I just pushed a fix. I will review it a bit more later

**Comment by beauwilliams** [comment]
I found the reason for splitright and below. We run wincmd p if its not set, basically we mimic the splitright/below and move to the new split.

It will always run the process args function now regardless

**Comment by beauwilliams** [comment]
Let me know its all good on your end. Just push the final fix 👍

**Comment by beauwilliams** [comment]
> Yes it works now, thanks

Perfect, thanks for the update
