### ISSUE TITLE
mis-sized floating window / panes with @camspiers/snap

### ISSUE THREAD

**Issue by alxndr** [beauwilliams/focus.nvim#45]
I am using [`@camspiers/snap`](https://github.com/camspiers/snap) as a file finder. I noticed that after installing `focus.nvim`, Snap's popup window, and the panes within it, are sized differently.

Intended behavior: there is a `.mov` video in [the Snap README](https://github.com/camspiers/snap/blob/4ed8f92/README.md#demo), which shows a floating window with three bordered panes: a tall "preview" on the right side, a single-line "input" at the bottom of the left side, and a "file list" at the top of the left side. Note that these bordered panes do not overlap.

Observed behavior: the bordered panes (described above) overlap, and the "preview" pane is widened such that its right side hits the edge of my Neovim instance — see screenshot below (note that I've blurred the text)

<img width="1440" alt="Screen Shot 2021-09-16 at 11 03 13 blur" src="https://user-images.githubusercontent.com/174307/133664018-bda9efdd-51c1-4e66-8c0a-bfc792bce83c.png">

**Comment by beauwilliams** [comment]
I know about this bug as I have used snap myself. I'll have a shot again at finding a solution. I spent a fair amount of time on it earlier

**Comment by beauwilliams** [comment]
@alxndr I have pushed a fix. It blocks filetypes with no name i.e '' default

I also made sure to re-run focus.resize() on WinLeave event

Note that if you set custom filetypes, it will override default (for now)

You can simply add '' to filetypes like my line from my configs

`excluded_filetypes = { "toggleterm", '' },`

**Comment by beauwilliams** [comment]
This should be fixed now. Reopen if there is issues 👍

**Comment by alxndr** [comment]
Thanks for the quick attention, the fix looks good to me!
