### ISSUE TITLE
Change of behavior FocusSplitNicely

### ISSUE THREAD

**Issue by cryptomilk** [beauwilliams/focus.nvim#47]
I've implemented FocusSplitNicely, when called it did a (v)split. So the current buffer is duplicated in the split!

With the current version the split opens an empty buffer! The README doesn't mention this change of behavior nor how I can control it to get the orignal behavior back!

**Comment by cryptomilk** [comment]
https://github.com/beauwilliams/focus.nvim/blob/master/lua/focus/modules/split.lua#L18

There should be a config option which you can set to get `enew`. This is not what you expect by default from a split!

**Comment by beauwilliams** [comment]
I will add this in today. I think I had it the other way round and was under the impression that a blank buffer is what people expected by default 😄

**Comment by beauwilliams** [comment]
I have made the change in the PR. I am not sure whether creating blank buffer should be default or not. I guess sticking with vim convention makes sense. But I personally disagree and think that the intuitive result of creating a new window is that its a blank buffer. 

Happy to go with what the users of focus think it should be.

**Comment by beauwilliams** [comment]
Interesting.. I just noticed github will only close one issue at a time automatically when referenced in a commit. Anyways, this is fixed now. Default behaviour = make copy of current window in new split (i.e default vim)

Lmk if issues or feel free to reopen 😄
