### ISSUE TITLE
Incorrect resizing when the same file is opened in two split windows at once

### ISSUE THREAD

**Issue by jonasstr** [beauwilliams/focus.nvim#50]
Hey, since a recent update Focus sometimes does the opposite of what it did in the past. It minimizes the current window instead of maximizing it! 

Weirdly enough, this only occurs when I have _the same_ file opened in two split windows.
Here is a GIF that shows this behavior: First I have the same file open twice -> the splits are resized incorrectly. Then I switch to a different buffer in the right split and now it behaves as expected.
![focus_bug](https://user-images.githubusercontent.com/40792180/134193271-b70a30a4-9a48-48de-a594-d144e8a6b531.gif)

I didn't really change anything in my setup. Any help would be greatly appreciated :)

**Comment by beauwilliams** [comment]
I know what it causing it. I need to use the WinEnter event. But it breaks snap unless I use vim.defer_fn.

I am going to use vim.schedule instead.

Now we can ensure that the resize() function is run after the filetypes and buffertypes are set.

**Comment by jonasstr** [comment]
Thank you, it's fixed now! :+1:
