### ISSUE TITLE
The latest update cause issue with NvimTree

### ISSUE THREAD

**Issue by evolify** [beauwilliams/focus.nvim#51]
After update.
It is normal when focus NvimTree.
But when focus file buffer. NvimTree become too big.

![image](https://user-images.githubusercontent.com/12669069/134337766-c7ed7163-1b4c-4d72-bfd9-891a9e9aee09.png)

**Comment by beauwilliams** [comment]
I've fixed the issue now. I need to sort out this edge case with the new api later.
