### ISSUE TITLE
Support cursorcolumn and colorcolumn toggling on focus

### ISSUE THREAD

**Issue by lxgreen** [beauwilliams/focus.nvim#54]
Similar to `cursorline`, it'd be nice to toggle `cursorcolumn` and `colorcolumn` options.

**Comment by beauwilliams** [comment]
We have a PR here. This might do the trick! I will get this added in for you. I am just catching up with things as I have been extremely busy lately. So now that some things out of the way, I will get around to sorting this out

https://github.com/beauwilliams/focus.nvim/pull/56

**Comment by beauwilliams** [comment]
Closed with f51e36c337651d3577a57e6d5dd7694e6b426fae 👍
