### ISSUE TITLE
winhighlight dims important text

### ISSUE THREAD

**Issue by nathanielks** [beauwilliams/focus.nvim#55]
When using `winhighlight`, important text (eg variable names) get set to black color in all buffers:

![Screenshot from 2021-09-28 17-45-34](https://user-images.githubusercontent.com/314009/135175888-21820919-8590-474e-ad83-667ef870893e.png)

![Screenshot from 2021-09-28 17-45-49](https://user-images.githubusercontent.com/314009/135175902-7b75ca53-e683-47b7-959e-2367c9c270cc.png)

Disabling `winhighlight` restores the correct colors.

**Comment by beauwilliams** [comment]
Let me see, I believe it is something to do with the highlight groups of whichever theme etc is setting it, we simply link them to existing highlight colors we don't set any in the code.
Have you managed to figure it out yet?
If not, you can redefine Focus highlight groups

**Comment by beauwilliams** [comment]
Please open if the issue is persisting. Thanks 👍
