### ISSUE TITLE
FocusSplit[Nicely] not functioning as expected when using `cmd` keyword

### ISSUE THREAD

**Issue by pard68** [beauwilliams/focus.nvim#57]
I'm not entirely sure if this is Focus' issue or the issue of a number of other plugins, but basically with some plugins, `ToggleTerm` and `Neogit` for example, when you open them with `:FocusSplit[Nicely] cmd ...` they open, but an extra window with an empty buffer is opened as well. I can open these plugins with their native commands without an issue, but I cannot open them with `:Focus` commands without this extra window.

Additionally, the `cmd` keyword seems to expect a single word/command not freaks out if you use multiple words, for example `:FocusSplitNicely cmd Neogit kind=split` just errors out. Same goes for calling lua functions, such as `:FocusSplit cmd lua require('neogit').open({kind=split})`. I've tried wrapping the command to be run in quotes and that doesn't seem to do anything to alleviate the problem. The error I get always seems to be the same, `E79: Cannot expand wildcards`.

**Comment by beauwilliams** [comment]
Yes my original implementation was a bit quick and dirty. I realise it does not extend very well. What I will do is have a look and try testing out how we can support commands such as `:FocusSplitNicely cmd Neogit kind=split`

Regarding the opening of blank buffers, that is a good question. It could be related to the plugin, well one thing is that the Focus commands will create buffers, so when creating a buffer that runs its own command to create a buffer you can end up with two. This could be a tricky problem to solve as I would have to hardcode in perhaps plugins that function like that to prevent those issues as there is not a standard way or API I have to work with.

**Comment by beauwilliams** [comment]
You can try it out now as I just merged #63 which should address this issue 👍
