### ISSUE TITLE
Question: is it possible to retain absolute line on unfocused windows?

### ISSUE THREAD

**Issue by dycw** [beauwilliams/focus.nvim#58]
Hi, thanks for a great plugin. I was wondering if it's possible to have both:

- absolute line numbers on unfocused windows, while
- use hybrid (absolute + relative) on the focused window?

Reason being I often find it helpful to issue move/copy commands with absolute line numbers.

**Comment by beauwilliams** [comment]
Hey! Apologies for delay. I have been extremely busy with university assingments and exams + other things. I can merge a PR today that should add this feature
