### ISSUE TITLE
diffview.nvim window gets focused

### ISSUE THREAD

**Issue by marcusbuffett** [beauwilliams/focus.nvim#59]
Resurrecting #42, looks like this is still happening. Have tried both with `{excluded_filetypes = {"DiffviewFiles"}}` and without, but it keeps looking like this:
<img width="1440" alt="Screen Shot 2021-10-30 at 12 48 02 PM" src="https://user-images.githubusercontent.com/1834328/139529806-f320dfd6-5ced-4644-82c9-cb40b26e7eb9.png">

Weirdly though, if I navigate to the other windows, then back to the diff view, it looks more normal:
<img width="1440" alt="Screen Shot 2021-10-30 at 12 49 13 PM" src="https://user-images.githubusercontent.com/1834328/139529843-d5426109-9262-4ac4-b03d-54101de563d5.png">

I'm wondering if diffview changes its filetype later or something? Would explain why focus.nvim expands it initially then doesn't later. It's just a random guess, and I don't have the knowledge to figure out if it's right. Let me know if there's anything else that would be useful to know.

Also, awesome project! Thank you 🙏

**Comment by dcy** [comment]
Me too

**Comment by beauwilliams** [comment]
Hmm, okay. No problem! I will get around to this ASAP. I have been extremely busy lately so I do appreciate your patience :)

Thank you so much for the support and I am glad you have found Focus to be of use to you!

**Comment by Mo8it** [comment]
The only bug preventing me from using Focus. Sad, because both Focus and Diffview are awesome!
I can try to help debugging if you give me some instructions @beauwilliams

**Comment by beauwilliams** [comment]
Closing as we are now discussing similar problem here https://github.com/beauwilliams/focus.nvim/issues/82

Relating to finding a way to make this plugin compatible for a wide range of plugins. This might require a rethink of how focus works.
