### ISSUE TITLE
Linenumbers in buftype popup

### ISSUE THREAD

**Issue by desdic** [beauwilliams/focus.nvim#61]
Hi,

You might want to add the buftype "popup" to the default excluced_buftypes since once the focus plugin is enabled you get a line number in the popup like this:

![2021-11-09_073314_674286659](https://user-images.githubusercontent.com/13243026/140906848-2b217dc4-3f39-4985-abbe-bf9cb247d20d.png)

this fixes it but I don't think anyone needs line numbers in a popup :)
```
excluded_buftypes = {"popup"}
```

**Comment by beauwilliams** [comment]
Thanks!! This is a great suggestion. Let me quickly test it today but I agree it makes sense to exclude the popups by default. I just have to make sure its not going to affect other plugins that use popups. But I agree it seems like that you wouldn't need line numbers in that case.
