### ISSUE TITLE
Error when using with nvim-bqf

### ISSUE THREAD

**Issue by kevintraver** [beauwilliams/focus.nvim#62]
When using with kevinhwang91/nvim-bqf, the previewer causes the following error:

**Error executing vim.schedule lua callback: vim/_meta.lua:170: E591: 'winheight' cannot be smaller than 'winminheight'**

Adding to the excluded_buftypes solves this for now:

`excluded_buftypes = { 'nofile', 'prompt', 'popup', 'quickfix'}`

**Comment by beauwilliams** [comment]
Are you still having this issue? It appears to be an issue with BQF adjusting the height on its own. I think the solution you posted is likely the best way around it. As we can't stop BQF changing height variables

**Comment by kevintraver** [comment]
Thanks for the explanation. Using `excluded_buftypes` works great.
