### ISSUE TITLE
Breaks pop-up interface of harpoon

### ISSUE THREAD

**Issue by sQVe** [beauwilliams/focus.nvim#64]
👋🏼,

If I have `focus.nvim` enabled it breaks the pop-up UI that `harpoon` uses. See https://github.com/ThePrimeagen/harpoon/issues/110

**Comment by sQVe** [comment]
Solved by adding `harpoon` to `excluded_filetypes`. Closing.

**Comment by catgoose** [comment]
Adding `harpoon` to `excluded_filetypes` does not seem to work for me:

![image](https://user-images.githubusercontent.com/21010072/184126327-7bc46543-d0ca-49f7-abd9-59ce078b831f.png)

**Comment by shendypratamaa** [comment]
> Adding `harpoon` to `excluded_filetypes` does not seem to work for me:
> 
> ![image](https://user-images.githubusercontent.com/21010072/184126327-7bc46543-d0ca-49f7-abd9-59ce078b831f.png)

same issue here added harpoon into excluded_filetypes not working as expected, for now im refer using telescope harpoon marks for showing a list of harpoon mark

**Comment by wassimk** [comment]
The fix doesn't work for me, either. I grepped the Harpoon codebase looking for other filetypes and only found `harpoon`. Any ideas?

**Comment by wassimk** [comment]
Here is how I was able to fix this for Harpoon. Disable focus before and after the Harpoon menu launches:

``` lua
vim.keymap.set('n', '<C-e>', function()
  require('focus').focus_disable()
  require('harpoon.ui').toggle_quick_menu()
  require('focus').focus_enable()
end)
```
