### ISSUE TITLE
Optional "minimum" width and height for the unfocused window(s)

### ISSUE THREAD

**Issue by pard68** [beauwilliams/focus.nvim#66]
I was thinking it would be nice to set an optional minimal width/height for unfocused windows. Sometimes, though rarely, the focused window takes up so much room that it renders my unfocused window(s) unreadable. Since I windows are always/usually contextually related to each other, this isn't good since I need to see what's in the other window. A solution I had thought of is setting a minimum window dimension so that the unfocused windows wouldn't go below a certain width, for example never make a window smaller than 80 characters wide.

**Comment by beauwilliams** [comment]
Good idea. Adding in the option now! I Tested it with 80 minwidth and works well.
