### ISSUE TITLE
Why is the first window bigger?

### ISSUE THREAD

**Issue by CoderKeung** [beauwilliams/focus.nvim#67]
My questions are as follows:
![image](https://user-images.githubusercontent.com/88510062/145973743-85a4a55a-fa36-4b65-8489-cdb52d37815b.png)
But when I open nvim-tree, it's normal：
![image](https://user-images.githubusercontent.com/88510062/145973911-a401bd6d-ffe7-4a84-adea-7cf1c92097a0.png)
Here is my configuration:

```
  use {
    'beauwilliams/focus.nvim',
    cmd = { "FocusSplitNicely", "FocusSplitCycle" },
    module = "focus",
    config = { function() require("focus").setup({signcolumn = false,excluded_filetypes = { 'toggleterm', 'NvimTree'}, minwidth =  20}) end }
  }
```

**Comment by beauwilliams** [comment]
If you wish you can set the width greater than what it is now.

The reason why the window was not completely 'crushed' in first screenshot is that there was available screen real estate.

When you added a 4th buffer window, the real estate was diminished. So this appears to be expected behaviour

Can you try this, open 4 splits. It should give you same result as screenshot #1.

**Comment by CoderKeung** [comment]
Thank you for your response !!!!! 

This problem seems to occur only in the case of three windows.

three windows: 
![Tree](https://user-images.githubusercontent.com/88510062/146126763-e5e396ba-f8c2-471c-8cd4-1333f1eb9903.gif)

more windows:
![Tree2](https://user-images.githubusercontent.com/88510062/146126776-5eb172a2-0300-416e-9f60-b75c0a68a045.gif)

**Comment by CoderKeung** [comment]
My configuration（ `minwidth = 30`）：
```
  use {
    disable = false,
    'beauwilliams/focus.nvim',
    cmd = { "FocusSplitNicely", "FocusToggle" },
    module = "focus",
    config = { function() require("focus").setup({signcolumn = false,excluded_filetypes = { 'NvimTree', 'diffview'}, minwidth = 30}) end }
  }
```

**Comment by beauwilliams** [comment]
Yeah so the first window will be bigger as this is how the vim core works when there is available screen real estate, it will expand the very leftmost window to take up the extra space.

Regarding the minwidth, that is also constrained too, as if there is not enough space available to support for example 3x windows @ 30 width + 1x window @ 150 width it will instead 'crush' the splits to fit into the display

**Comment by beauwilliams** [comment]
@CoderKeung there is no need to add nvim tree to excluded filetypes.

See my config (I used nvim tree)

`					excluded_filetypes = { 'fterm', 'term', 'diffviewfiles' },
`

**Comment by beauwilliams** [comment]
Closing as stale issue
