### ISSUE TITLE
E5113: Error while calling lua chunk: attempt to concatenate field 'blacklist' (a table value)

### ISSUE THREAD

**Issue by hexh250786313** [beauwilliams/focus.nvim#68]
E5113: Error while calling lua chunk: ...re/nvim/plugged/focus.nvim/lua/focus/modules/autocmd.lua:48: attempt to concatenate field 'blacklist' (a table value)

![image](https://user-images.githubusercontent.com/26080416/146627122-c50bc27c-12bc-42d1-b02b-058db62bdc55.png)

```lua
-- config
require("focus").setup()
```

**Comment by beauwilliams** [comment]
@hexh250786313 Please pull latest changes and let me know if this issue still persists. It is an issue caused during a merge conflict I resolved earlier.

I have already fixed it

**Comment by beauwilliams** [comment]
Please open again if you are still having this issue 👍
