### ISSUE TITLE
window resizes even if uninstalled

### ISSUE THREAD

**Issue by aravind2612krishna** [beauwilliams/focus.nvim#69]
Even if I remove the plugin, my neovim seems to automatically resize the windows on winenter. I checked the autocmds for WinEnter, and they seem clean. Any help on debugging this would be appreciated.

**Comment by aravind2612krishna** [comment]
Apologies, this seems to be due to mksession storing the winsizes, and not the plugin itself.

**Comment by beauwilliams** [comment]
All good 👍
