### ISSUE TITLE
Disable Auto-Resizing optionally

### ISSUE THREAD

**Issue by L2AsHdz** [beauwilliams/focus.nvim#71]
I've been using the plugin but I've been having some problems specifically with the auto-resizing option, I would like to be able to disable this feature and still use the others

**Comment by beauwilliams** [comment]
Done 👍 You can configure using `require("focus").setup({autoresize = false})`

**Comment by L2AsHdz** [comment]
With fzf-lua which before was unusable now works perfect :3 now when using diffview for some reason it keeps changing the default dimensions of the buffers, but it doesn't make it unusable so **thanks a lot!!!**
