### ISSUE TITLE
Vifm Problems while focus change

### ISSUE THREAD

**Issue by ChrisGitIt** [beauwilliams/focus.nvim#76]
Hi and sorry for a improper error reporting. Not sure exactly how to start.

So I use vifm (https://vifm.info) as my primary file manager in Neovim.

When i use ":VsplitVifm", a split window is opened with vifm as file manager within.
Using vifm works without problems, but as soon as focus to another buffer and then back to the vifmsplit, vifm stops working (no directory browsing, no command line etc.)

When I use :q to quit the vifm buffer, its not possible to reopen another vifm buffer (buffer is already existing).

In order to resume normal working for any vifm buffers, the (old vifm) buffer needs to be close via ":bd!" (just ":bd" does not seem to work somehow ..)

I tried some exclude_*:
```
excluded_filetypes = {"toggleterm","terminal","term", "VsplitVifm"},
excluded_buftypes = {"help", "vifm", "nofile", "prompt", "popup", "terminal","term","VsplitVifm"}
```
but nothing seems to help.

Any help or tips are greatly appreciated!

Bye the way: NICE Plugin!

**Comment by beauwilliams** [comment]
Closing as we will follow up on plugin compatibility issues here https://github.com/beauwilliams/focus.nvim/issues/82
