### ISSUE TITLE
Exclude buftype of iron.nvim

### ISSUE THREAD

**Issue by timoleistner** [beauwilliams/focus.nvim#81]
I'm using [iron.nvim](https://github.com/hkupty/iron.nvim) for interactive REPLs.
It is opening a terminal which I'm trying to exclude from focus.nvim so that it wont change its size when focused.
The (thankfully) provided `:lua print(vim.bo.buftype)` command returns `terminal` which is why I've configured focus.nvim like this:
```
use({
    "beauwilliams/focus.nvim",
    config = function()
        require("focus").setup({
            excluded_buftypes = { "terminal" },
        })
    end
})
```
(I've also tried with the filetype command but of course the terminal wont return a filetype.)

**Comment by DrKGD** [comment]
For Telescope, try adding `TelescopePrompt` to the ignored filetypes
```
excluded_filetypes = {'TelescopePrompt'}
```
Not sure this _correctly addresses the problem_ but it is a fix nonetheless.

Also I was having a similiar problem with regarding [Harpoon](https://github.com/ThePrimeagen/harpoon).
In case anyone is wondering which ft you should ignore: `harpoon`
```
excluded_filetypes = {'TelescopePrompt', 'harpoon'}
```

Not sure there is a direct solution for the `term` filetype, as stated in the [FAQs](https://github.com/beauwilliams/focus.nvim#faq):

> This is an issue with how and when the filetype is set for a buffer.

Maybe I am missing something but I am willing to switch to ToggleTerm, just in case.

**Comment by beauwilliams** [comment]
Let me take some time to test out REPL.nvim. I agree that filetype exclusion can unfortunately be hit and miss as there is no standard way that plugins create their buffers. Some plugins are easy to exclude, some have implementations that make things difficult.

I've used vim.schedule to only so slightly delay focus loading on buffers to give time for plugins to register buffer filenames so in turn focus can read them and react conditionally.

I personally use ToggleTerm myself, and never have issues with filetype exclusion

**Comment by beauwilliams** [comment]
Closing as we will follow up discussion on plugin compatibility here https://github.com/beauwilliams/focus.nvim/issues/82
