### ISSUE TITLE
bug with autoresize after new buffer opening from telescope

### ISSUE THREAD

**Issue by kaiphat** [beauwilliams/focus.nvim#87]
I have this case
![image](https://user-images.githubusercontent.com/53742299/173561912-3e71d48f-b969-4f57-8fae-46fc3449601a.png)
Then i open new buffer from telescope. On that screenshot last split window has 1 pixel width.
![image](https://user-images.githubusercontent.com/53742299/173561998-5dd6a7cd-98d0-44e6-9f49-71dde2410499.png)
When i move cursor right, all is okey
![image](https://user-images.githubusercontent.com/53742299/173562188-666c037b-3567-4f66-a7d3-154a6d95d351.png)

**Comment by beauwilliams** [comment]
Let me see, is this specifically when you open a new split from the telescope prompt?

But opening something from the telescope prompt normally (i.e into the split that you were in when entering telescope) is no problem?
