### ISSUE TITLE
feature: ignore min_width when there isn't enough space

### ISSUE THREAD

**Issue by kaiphat** [beauwilliams/focus.nvim#88]
If i want open a lot of splits i will get that error:
![image](https://user-images.githubusercontent.com/53742299/173562752-6108b15c-60ca-436a-8896-0805dcc411c0.png)

But i need use min_width option, because without it, my not focused splits will be too small.

**Comment by beauwilliams** [comment]
This is a tough one. We will need to keep track of N number of splits open and the W width of the users display.

We can then take W/N and check if it is < min_width. If so, we can reduce min_width by an increment. But this can lead us to other issues. Let me think about a solution
