### ISSUE TITLE
rouge print statement in utils

### ISSUE THREAD

**Issue by sagarc03** [beauwilliams/focus.nvim#92]
https://github.com/beauwilliams/focus.nvim/blob/67000175608d83801bfacea0f60546c8cf1433ab/lua/focus/modules/utils.lua#L54

**Comment by sagarc03** [comment]
looks like there is already a PR #91

**Comment by p4-k4** [comment]
Please merge the PR @beauwilliams! Thanks

**Comment by beauwilliams** [comment]
All done! Thanks for pointing it out :)
